sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.4.1
cache:
  bundler: true
  directories:
    - flow_test

install:
  - bundle install
  
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake test
  - bundle exec rake test:$TEST_SUITE
  #/test.sh
  
deploy:
  skip_cleanup: true
  
git:
  depth: 3
branches:
  only:
    - master
    #提供正则匹配分支
    #- /^char.*$/
bundler_args: --without development debug #不安装debug gem
bundler_args: --retry 5 #如果网络超时，可以retry
env: #可以分开跑测试
  - TEST_SUITE=units
  - TEST_SUITE=integeration
  
    
    

