sudo: required
#可以在docker上跑
services:
  - docker
language: ruby
#测试在docker上跑
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine #
  - docker pull carlad/sinatra
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
rvm:
  - 2.3.1
  - 2.4.1
cache:
  bundler: true
  directories:
    - flow_test

install:
  - bundle install
  
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake test
  - bundle exec rake test:$TEST_SUITE
  #/test.sh
  
deploy:
  skip_cleanup: true
  
git:
  depth: 3
  
branches:
  only:
    - master
    #提供正则匹配分支
    #- /^char.*$/
bundler_args: --without development debug #不安装debug gem
bundler_args: --retry 5 #如果网络超时，可以retry
env: #可以分开跑测试
  - TEST_SUITE=models
  - TEST_SUITE=integeration
  
    
    

